PhotonVision/photonvision-docs

source/docs/getting-started/pipeline-tuning/thresholding.rst
Erode and Dilate is being removed from PhotonVision, this is to match that. Only merge once the change happens in the UI.
=> Removed Erode and Dilate Documentation

source/docs/getting-started/installation/coprocessor-image.rst, source/docs/hardware.rst, source/docs/other/index.rst, source/docs/other/known-issues.rst, source/docs/programming/photonlib/creating-photon-camera.rst, source/docs/programming/photonlib/simple-pipeline-result.rst, source/docs/programming/photonlib/util-calculations.rst
This should be everything, please check over the PhotonLib parts closely as I deleted a few sections (to make it more clear to the user that they should be going from PipelineResult to TrackedTarget and then getting Yaw, Pitch, etc. unlike before where they got it from a PhotonCamera method.
Hardware documentation still isn't optimal yet in terms of organization but at least it still has all the information that we need.
Known issues page documents PS3ye stuff and has an empty software section
=> Add AngryScanner IP docs, update PhotonLib docs, reorganize hardware docs, add known issues page

source/docs/getting-started/Settings.rst
Changes:
https://docs.photonvision.org/en/latest/docs/getting-started/installation/coprocessor-image.html?highlight=IP#troubleshooting
to 
https://docs.photonvision.org/en/latest/docs/getting-started/installation/coprocessor-image.html?highlight=IP#troubleshooting-setting-a-static-ip
=> Fixes broken link on settings page

requirements.txt
I needed to install it after running `pip install -r requirements.txt` in order to build successfully.
=> Add sphinx_rtd_theme to requirements.txt

source/docs/programming/photonlib/simulation.rst
Per [Jason on discord](https://discord.com/channels/725836368059826228/725848198794706994/820278569233678367) - object name incorrect in Java in the instantiation block.
=> Fix variable name in simulation docs

source/docs/programming/photonlib/simple-pipeline-result.rst
=> missing `result` in code samples for latency

source/docs/getting-started/installation/limelight.rst
Clarify the static IP step.
Move the step of downloading hardware configs to before the user connects to the robot.
=> Clarify network and hardware config steps

source/docs/programming/photonlib/creating-photon-camera.rst, source/docs/programming/photonlib/simulation.rst, source/docs/programming/photonlib/util-calculations.rst
=> Updated permalinks

source/docs/getting-started/installation/networking.rst, source/docs/getting-started/installation/sw_install/gloworm.rst, source/docs/getting-started/installation/sw_install/limelight.rst
In the latest Photon release, the hostname has changed to photonvision.local
=> Update gloworm hostname to photonvision

source/docs/programming/photonlib/robot-pose-estimator.rst
`AprilTagFieldLayout.loadFromResource` returns an `AprilTagFieldLayout` meaning passing it back into the constructor is not needed and also a syntax error as `AprilTagFieldLayout` has no defined constructor for `AprilTagFieldLayout(AprilTagFieldLayout))`
=> Correct Typo & initialize AprilTagFieldLayout correctly

source/docs/programming/photonlib/getting-target-data.rst
Before, it was getYaw() before describing getSkew(). That is not correct.
=> change incorrect instance of getYaw()

source/docs/installation/sw_install/advanced-cmd.rst
Replacement for PR 301 which seems to have gone bad.
=> Add a note about big.LITTLE CPUs and "AllowedCPUs".

source/docs/programming/photonlib/robot-pose-estimator.rst, source/docs/simulation/simulation.rst
more of a subjective change, but will make writing vision code for 2024 easier. 
I changed all references of ``AprilTagFields.k2023ChargedUp`` to ``AprilTagFields.k2024Crescendo``
=> Use the 2024 Apriltag Field Layout instead of 2023

source/docs/programming/photonlib/using-target-data.rst
on the page: using-target-data
the description correctly states that "``estimateFieldToRobotAprilTag(...)`` returns your robot’s Pose3d" however the example shows the function returning a Pose3D instead. Likely a caps typo.
I have fixed the example so that it shows the correct return type.
=> Java example returned type is incorrect in example. (page: using-target-data)

source/docs/installation/sw_install/windows-pc.rst
PhotonVision does not work properly with integrated laptop cameras. When trying to run PhotonVision on windows with an integrated laptop webcam driver enabled, it simply crashes with no error message. Adding a warning will help prevent users from experiencing the same issue.
Fixes https://github.com/PhotonVision/photonvision/issues/1165
=> Add warning about using integrated laptop cameras on windows

source/docs/programming/photonlib/robot-pose-estimator.rst
Use AprilTagFields/LoadAprilTagLayoutField to avoid unchecked IOException 
Provide C++ example using provided field instead of custom field. Even if people wanted a custom field, it's likely to be in the form of a JSON file rather then defining in code.
Update WPILIb doc links from beta to release
https://www.chiefdelphi.com/t/apriltagfieldlayout-json-file-for-c/452553 
https://www.chiefdelphi.com/t/photonvision-2024-release/448635/74
=> Update AprilTagLayout example code

source/docs/programming/photonlib/adding-vendordep.rst, source/docs/programming/photonlib/getting-target-data.rst
So basic it's wearing ugg boots while ordering a vanilla latte.
=> basic python docs

source/docs/programming/photonlib/getting-target-data.rst
Partially fixes #315, Java and C++ fixes have to be made on the main repo because of RLI usage
=> Fix python camera naming on getting target data page

source/docs/apriltag-pipelines/2D-tracking-tuning.rst, source/docs/apriltag-pipelines/3D-tracking.rst, source/docs/apriltag-pipelines/multitag.rst, source/docs/contributing/photonvision/build-instructions.rst, source/docs/hardware/selecting-hardware.rst, source/docs/installation/index.rst, source/docs/objectDetection/about-object-detection.rst, source/docs/troubleshooting/common-errors.rst
=> Fixed a few small spelling + grammar mistakes

source/docs/additional-resources/best-practices.rst
From a real story at competition:
We lost an SD Card during eliminations at our last competition, but thankfully remembered to create a snapshot of our settings using the built-in `Export Settings`/`Import Settings` tools on the Settings page. We were able to restore our OrangePi's functionality by following simple backup procedure. Hopefully this information can help other teams as well.
=> Add Import/Export Settings steps for competitions under `Best Practices`

source/conf.py, source/docs/hardware/picamconfig.rst, source/docs/installation/sw_install/gloworm.rst, source/docs/installation/sw_install/orange-pi.rst, source/docs/installation/sw_install/raspberry-pi.rst, source/docs/installation/sw_install/snakeyes.rst, source/docs/pipelines/output.rst
Update links to balena etcher to point to 1.18.11 and change the warning against older versions to only warn against versions older than 1.18.11, as it is not the newest version.
=> Update balena etcher references to point to 1.18.11 closes PhotonVision/photonvision-docs#357
