PhotonVision/photonvision-docs

source/_static/css/pv-rtd.css
source/conf.py
source/docs/developers/build-instructions.rst
source/docs/developers/index.rst
source/index.rst

Add tabs to build instructions and minor fixes

---

requirements.txt
source/conf.py

No real reason not to support this.
Also `requirments.txt` should probably specify a version for ***all*** requirements

Add ogp support and add versions for requirements

---

source/docs/programming/nt-api/nt-api.rst
source/index.rst

Add NT API table

---

source/docs/getting-started/index.rst
source/docs/getting-started/installation/advanced-cmd.rst
source/docs/getting-started/installation/index.rst
source/index.rst

Add advanced systemd and Java information

---

.github/workflows/main.yml
source/docs/programming/nt-api/nt-api.rst
source/docs/programming/photonlib/creating-photon-camera.rst

Added documentation describing the image save command NT entry usage and behavior.

Added image save docs

---

.github/workflows/main.yml

It's not like we're doing controls math...

Kill LaTeX

---

requirements.txt
source/_static/css/pv-rtd.css
source/conf.py

This updates the configuration and gets rid of the old CSS to use the Furo theme. To learn more about furo, see [here](https://github.com/pradyunsg/furo).

Changed documentation theme from Sphinx Material to Furo

---

source/docs/programming/config/config.rst

Single-File Import Documentation

---

source/docs/other/known-issues.rst
source/docs/programming/nt-api/nt-api.rst

Added additional details about LED control limitations with multiple cameras.
Addresses this guy: https://github.com/PhotonVision/photonvision-docs/issues/62

LED Control Limitation Details

---

source/index.rst

Added space between FIRST and Robotics

---

source/docs/examples/aimandrange.rst
source/docs/examples/aimingatatarget.rst
source/docs/examples/gettinginrangeofthetarget.rst

Things now point to the monorepo rather than the archived repo

Fixed remote literal includes for examples

---

source/docs/examples/aimandrange.rst
source/docs/examples/aimingatatarget.rst
source/docs/examples/gettinginrangeofthetarget.rst
source/docs/programming/config/config.rst

Removes odd looking lines on the Configuration Directory page and added bullet points.
Old:
New:

Fixed Configuration Directory Formatting

---

source/docs/programming/photonlib/creating-photon-camera.rst
source/docs/programming/photonlib/simulation.rst
source/docs/programming/photonlib/util-calculations.rst

Adds RLIs for PhotonUtils, Simulation, and other pages.
Closes #87

Added RLIs

---

source/docs/other/contributing/photonvision/build-instructions.rst

Fixed build documentation

---

source/docs/programming/photonlib/util-calculations.rst

Added Pose2D documentation

---

source/docs/getting-started/Networking.rst
source/docs/getting-started/UsingPhotonVisionAtCompetition.rst
source/docs/getting-started/index.rst

Closes #99 
I think I've got the ports right but a look over would be nice.

Added networking and port forwarding

---

source/docs/programming/photonlib/controlling-led.rst

Changed LEDMode to VisionLEDMode in the docs.

Updated LED Mode docs

---

source/docs/examples/simaimandrange.rst
source/docs/examples/simposeest.rst
source/docs/getting-started/installation/pc-installation.rst
source/docs/getting-started/pipeline-tuning/calibration.rst
source/docs/hardware.rst
source/index.rst

The only redirects I left were the git.io ones since those appear to be for giving the user less to manually type into a terminal.

Resolve redirects and update RLIs

---

source/conf.py
source/docs/getting-started/Settings.rst
source/docs/getting-started/about/advantages.rst
source/docs/getting-started/installation/coprocessor-image.rst
source/docs/getting-started/pipeline-tuning/output.rst
source/docs/hardware/customhardware.rst
source/docs/hardware/index.rst
source/docs/hardware/supportedhardware.rst
source/docs/programming/photonlib/creating-photon-camera.rst
source/docs/programming/photonlib/simulation.rst
source/index.rst

closes https://github.com/PhotonVision/photonvision-docs/issues/120

Hardware .json docs

---

source/docs/examples/simposeest.rst
source/docs/integration/advancedStrategies.rst
source/docs/integration/background.rst
source/docs/integration/index.rst
source/docs/integration/simpleStrategies.rst
source/index.rst

Building off of #129 , builds up a section explaining the thought processes behind integrating photonvision into a robot.

Add "Integration" Section

---

source/docs/hardware/customhardware.rst

Added sentence on custom leds

---

source/docs/getting-started/installation/romi.rst

Added romi writeable note

---

source/docs/getting-started/installation/coprocessor-image.rst

Added docs for updating PhotonVision

---

source/docs/examples/simposeest.rst

Added tab syncing on simposeest example

---

source/docs/programming/nt-api/nt-api.rst

Clarifies confusion on server mode and when we should/should not have it on. 
Closes #122

Added NetworkTables info

---

source/docs/getting-started/installation/coprocessor-image.rst
source/docs/hardware/supportedhardware.rst

Updated install docs to point to Snakeyes install stuff

Update snakeyes install docs to account for img build

---

source/conf.py

This is needed to get the build to pass

Remove sphinx-tabs from conf.py

---

requirements.txt
source/conf.py

This should hopefully fix the issue where docs do not build and won't update.

Reverted conf and requirements changes

---

source/docs/getting-started/installation/coprocessor-image.rst
source/docs/getting-started/installation/limelight.rst
source/docs/getting-started/installation/romi.rst
source/docs/hardware/supportedhardware.rst
source/index.rst

Fix broken gloworm.vision links

---

source/docs/hardware/supportedhardware.rst

Updated hardware page

---

source/docs/getting-started/best-practices.rst
source/index.rst

Closes #197 
If Limelight users can get best practices, why can't PhotonVision users?

best practice

---

source/docs/hardware/supportedhardware.rst

Should I break this into separate page? its one big page with a lot of little things

update hardware page

---

source/conf.py
source/docs/getting-started/installation/sw_install/gloworm.rst
source/docs/getting-started/installation/sw_install/index.rst
source/docs/getting-started/installation/sw_install/linux-pc.rst
source/docs/getting-started/installation/sw_install/mac-os.rst
source/docs/getting-started/installation/sw_install/orange-pi.rst
source/docs/getting-started/installation/sw_install/other-coprocessors.rst
source/docs/getting-started/installation/sw_install/raspberry-pi.rst
source/docs/getting-started/installation/sw_install/snakeyes.rst
source/docs/getting-started/installation/sw_install/windows-pc.rst

~~I messed up the commits so dont merge yet~~
Good to merge.

Fix install

---

source/docs/examples/apriltag.rst
source/docs/examples/simposeest.rst

Some minor errors that stood out when reading the example code section.

Fix examples documentation

---

source/docs/programming/photonlib/robot-pose-estimator.rst

Adding MULTI_TAG_PNP to the docs
Currently a user must read the javadoc or release notes to find this feature.

add MULTI_TAG_pnp to docs

---

source/docs/contributing/photonvision/build-instructions.rst

they were single-lining on the webpage

Better formatting for build instructions

---

source/docs/apriltag-pipelines/detector-types.rst

Found a small spelling mistake when reading the docs, decided to send in a PR.

Fix small spelling mistake

---

source/docs/installation/sw_install/limelight.rst

Explain why there is no LL3 hardware config
